language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 4.0"
    - rvm: 2.4.1
      env: PUPPET_VERSION="~> 5.0"

script: 'bundle exec rake tests'

notifications:
  email:
    on_failure: change
    on_success: never
  slack:
    rooms:
      - thecomfyseat:WL1DXdQiUfriFxuS9otGGvKf
      - uwg-techs:sdP80CwKyGdijFfTG9Vmjncl